//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muavin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Muavin()
        {
            this.Sefer = new HashSet<Sefer>();
        }
    
        public int id { get; set; }
        public string MuavinAd { get; set; }
        public string MuavinSoyad { get; set; }
        public string TcNo { get; set; }
        public string TelNo { get; set; }
        public System.DateTime Yas { get; set; }
        public Nullable<bool> Silme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sefer> Sefer { get; set; }
    }
}
