//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sefer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sefer()
        {
            this.AktifSefer = new HashSet<AktifSefer>();
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int id { get; set; }
        public string NeredenNereye { get; set; }
        public int KalkisId { get; set; }
        public int VarisId { get; set; }
        public string AraDurak { get; set; }
        public int OtobusId { get; set; }
        public int KaptanId { get; set; }
        public int MuavinId { get; set; }
        public decimal SeferUcret { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Saat { get; set; }
        public Nullable<bool> Silme { get; set; }
        public Nullable<int> DoluSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktifSefer> AktifSefer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Kaptan Kaptan { get; set; }
        public virtual Muavin Muavin { get; set; }
        public virtual Otobus Otobus { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual Sehir Sehir1 { get; set; }
    }
}
