//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yolcu
    {
        public int id { get; set; }
        public string YolcuAd { get; set; }
        public string YolcuSoyad { get; set; }
        public string TcNo { get; set; }
        public string TelNO { get; set; }
        public string Cinsiyet { get; set; }
        public string YolcuMail { get; set; }
        public Nullable<bool> Silme { get; set; }
    }
}
